openapi: 3.0.1
info:
  title: Products API
  version: 1.0.0
servers:
  - url: http://backend.vm1.test/api
    description: Backend API server
paths:
  /products:
    get:
      operationId: products.list
      summary: Returns a list of all products
      responses:
        "200":
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      example: "Aloe Vera"
                    description:
                      type: string
                      example: "Gyógyító tulajdonságokkal rendelkező pozsgás. Nagyon kevés vizet igényel és a gélje bőrápolásra is használható."
                    price:
                      type: number
                      example: 2500
